spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: wlstjr57
    url: jdbc:mariadb://localhost:3306/sogi_cms

  jpa:
    hibernate:
      ddl-auto: create # 엔티티를 새로 만들었을 때에만 create, create-drop으로 설정하고 이외에는 update를 사용하자. 인가 설정과 엮여 있어 인가가 제대로 돌아가지 않는 이슈가 있다. (참고 - FilterSecurityInterceptorConfiguration.java)
#    show-sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true